ao-org/argentum-online-server

Codigo/General.bas
Saco árboles de la transparencia, esto esta hardcodeado deberiamos sacarlos a un *.ini
=> Remove alpha from tree

Codigo/Protocol.bas
saco el /Dar a todos los rangos menor a Admin, solo los Admin pueden dar premios hay un log para registra las entregas
=> Elimino /dar 

Codigo/Protocol.bas, Codigo/TCP.bas
don't remove frags when expeling from faction
=> reset values for faction armor when forgiven

Codigo/FileIO.bas, Codigo/Logging.bas, Codigo/Protocol.bas, Codigo/modNetwork.bas
Add support for feature toggles and some network logs
=> Feature toggle

Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol_Writes.bas, Codigo/Trabajo.bas, Codigo/modNetwork.bas
=> Add debug data for network issue

Codigo/CustomScenarios.bas, Codigo/Protocol_GmCommands.bas, Codigo/ScenarioDeathMatch.cls, Codigo/ScenarioKillNpc.cls
=> test if there is and active event before creating a new one

Codigo/CustomScenarios.bas, Codigo/ModLobby.bas, Codigo/Protocol_GmCommands.bas, Codigo/ScenarioDeathMatch.cls, Codigo/ScenarioKillNpc.cls, Codigo/ScoreBoard.cls, Codigo/SistemaCombate.bas
Fix isevent active bug
add force reset event just in case some event fails to close properly
=> Fix some index oveflow issues

Codigo/General.bas, Codigo/InvUsuario.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Trabajo.bas
Replaced DarCuerpoDesnudo(userindex ) by SetNakedBody( ref t_User)
=> Minor refactoring SetNakedBody

Codigo/Admin.bas, Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/MODULO_NPCs.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol_Writes.bas, Codigo/SistemaCombate.bas
=> move stun values from const to balance resource

Codigo/clsClan.cls, Codigo/modGuilds.bas
elimina el personaje inexistente de la lista de miembros
=> fix personaje bugeado en clan

Codigo/InvUsuario.bas, Codigo/Protocol.bas, Codigo/ScenarioDeathMatch.cls
fix inventory loot position
fix deathmatch potion stack spawn to scale the amount with the number of players instead of the size kick the user when a character is sold on MAO
=> some small fixes

Codigo/CharacterPersistence.bas, Codigo/Database_Queries.bas, Codigo/InvUsuario.bas, Codigo/MODULO_NPCs.bas, Codigo/ModRetos.bas, Codigo/Protocol.bas, Codigo/Protocol_GmCommands.bas, Codigo/SistemaCombate.bas
Add more logs to gm commands
Fix some damage message that were missing
fix last_logout field from user to store epoch time fix and overflow on retos
fix the boundaries from setnpcref, the first npc was always a invalid reference
=> some fixes

Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/InvUsuario.bas
Al dejar de ser newbie lo mandamos a una isla segura para explicar como seguir
=> Fix salida del DN a la isla Renacimiento

Codigo/Protocol.bas
validate if the target user is in the whisper area before checking if it is death to prevent abuse
=> move whisper to death user validation

Codigo/Declares.bas, Codigo/EffectsOverTime.bas, Codigo/FileIO.bas, Codigo/IBaseEffectOverTime.cls, Codigo/InvUsuario.bas, Codigo/LocaleDef.bas, Codigo/Matematicas.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol.bas, Codigo/SistemaCombate.bas, Codigo/StatModifier.cls, Codigo/TCP.bas, Codigo/UpdateHpOverTime.cls, Codigo/modHechizos.bas, Server.VBP
add new effect to update modifiers
=> Add stats modifier support for damage bonus and reduction

Codigo/Declares.bas, Codigo/MODULO_NPCs.bas, Codigo/ModQuest.bas, Codigo/Protocol.bas
add required class limit to quest requirements
=> add required class limit to quest requirements

Codigo/Acciones.bas
Fix Total Points in Fishing Book
=> Fix Total Points in Fishing Book

Codigo/Protocol.bas
=> Removed unused packetIDs

Codigo/General.bas, Codigo/LocaleDef.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/ReferenceUtils.bas, Codigo/SistemaCombate.bas, Codigo/clsTrap.cls
fix incinerate damage
add messages for traps
fix duplicated damage when attacking another user
=> Fix some damage message issues

Codigo/AI_NPC.bas, Codigo/FileIO.bas
if the NPC can attack with magic and is next to it you can hit him
=> attack if stuck to the user

Codigo/ApplyEffectOnHit.cls, Codigo/DrunkEffect.cls, Codigo/Modulo_UsUaRiOs.bas
fix some buff icons not stacking properly or removing itself when the effect is removed
=> Fix charindex update when user is in a group

Codigo/General.bas
=> Fix de EsArbol

Codigo/AI_NPC.bas, Codigo/Admin.bas, Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/InvUsuario.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol.bas, Codigo/Trabajo.bas, Codigo/modHechizos.bas
fix some creating keep attacking while paralized
=> add support to keep old invisiblity on some maps

Codigo/Protocol_GmCommands.bas
Message to close client only for admin and god
=> Mensaje solo Admin y dios

Codigo/InvUsuario.bas, Codigo/LocaleDef.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol.bas, Codigo/ScenarioDeathMatch.cls, Codigo/SistemaCombate.bas, Codigo/modHechizos.bas
use items while stun is active
only use bindable spells on group frame
prevent armor to be applied twice on stab
=> some balance changes

Codigo/Admin.bas, Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/LocaleDef.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/modHechizos.bas
1)add time limit for recent kills
2) add faction score to /est command
3) add direct bonus damage for magic bonus (to add damage to spells instead of percent damage)
=> update faction score system

Codigo/General.bas, Codigo/Penas.bas, Codigo/Protocol.bas, Codigo/Protocol_GmCommands.bas, Codigo/UnitClient.bas, Codigo/frmMain.frm, Codigo/frmServidor.frm, Codigo/modNetwork.bas
Removed IP_BlackList
Ther server must not waste time dealing with banning IPs because it's not scalable, it's confusing to know where the IP has been banned and a security risk.
IP banning has to be done via Firewall on a different layer and part of the architecture
=> Removed IP_BlackList

Codigo/Protocol.bas
=> Mensajes control macro

Codigo/Modulo_UsUaRiOs.bas
When the level of the enemy is a few level below yours it will give you negative points.. it should at least give you 1 point in any case.
=> Fix negative scores

Codigo/Modulo_UsUaRiOs.bas
When you were at the edge of the screen invi and go to other play view it won't play the sound as it was using old position for checks.
=> Fix invi step no playing at edge

Codigo/InvUsuario.bas
Al estar muerto e ingresar no aparecia la barca o traje.
=> Fix trajes muerto

Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol_GmCommands.bas
User position information only Administrator and God
=> User position information only Administrator and God

Codigo/TCP.bas
=> Fix Items Principiantes

Codigo/Protocol.bas, Codigo/modGuilds.bas
Ahora se funda clan con LVL 25 - 35 Liderazgo - 4 Gemas
=> Cambios Fundar Clan

Codigo/frmMain.frm
Fix HoraFantasia_Timer type missmatch
=> Fix HoraFantasia_Timer type missmatch

Codigo/TCP.bas
Agregado Escudo Principiante Al Cazador
=> Agregado Escudo Principiante Al Cazador

Codigo/CharacterPersistence.bas, Codigo/Declares.bas, Codigo/Protocol.bas, Codigo/modDatabase.bas, Server.VBP
=> Limites de slots dependiendo subscripcion de cuenta.

Codigo/CharacterPersistence.bas, Codigo/Protocol.bas
Capped num PCs per patron tier
=> Notify client about max PCs

Codigo/TCP.bas
Se cambia la entrega del objeto, por el nuevo con los nuevos dateos de ropajes.
=> Update Armadura/Tunica Principiante

Codigo/Hogar.bas
=> Fix traje de caucho

Codigo/modHechizos.bas
Reverts ao-org/argentum-online-server#537
es muy beneficioso para el agite, que esperen que suba sola, esto es porque cuando lo reviven al toque ya puede usar hechizo.
=> Revierto stamina al resucitar con hechizo.

Codigo/Declares.bas
Reverts ao-org/argentum-online-server#536
Revierto a pedido de @ReyarB
=> Revert "body enumeration"

Codigo/GameLogic.bas
Added missing Exit Function in PacktIdToString
=> Added missing Exit Function in PacktIdToString

Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/GameLogic.bas
Limit access to maps to Patreon only
=> Only patreon

Codigo/Trabajo.bas
Arregla el bug que al crear un objeto que requiere leña élfica y leña común, consumía la leña élfica con las cantidades de leña común
=> Fix carpinteria

Codigo/Hogar.bas, Server.VBP
Fixed num ciudades, now are 7 with forgat with gobernor
=> Fixed num ciudades, now are 7 with forgat with gobernor

Codigo/modNetwork.bas
Se aplicaron cambios en los parametros de la definicion Kick
=> Fix Server Kick

Codigo/TCP.bas
- Saco la condición de armadura/túnica del principiante en función de la raza ya que ahora es indistinto
- Agrego daga del principiante para paladín
- Agrego anillo del principiante para guerrero
- Corrijo casco de lobo para druida
=> Actualizo items principiante

Codigo/TCP.bas
Actualizo el mapa-x-y de nacimiento cuando el personaje tiene Hogar inicial en Forgat y Arghal. Actualizo el mapa de forgat al nuevo mapa.
=> Actualizo tile de nacimiento Forgat y Arghal

Codigo/ModCola.cls
Added timestamps to /gm requests.
Evidence:
=> [ISSUE-570] [SERVER] Agregarle fecha y hora a la consulta que nos llegan al PanelGM

Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/MODULO_NPCs.bas, Codigo/SistemaCombate.bas
Modifico la carga del dateo de balance para solo utilizar balance.dat y dejar de usar balance2.dat
=> Unifico balance y balance2

Codigo/Trabajo.bas
- Saco requisito para usar la red hardcodeado de 80 skills, ahora se limita por nivel en obj.dat
- Hago que la red de pesca solo funcione en áreas de pesca
- Permito pescar con caña en zona insegura
=> Permito pescar con caña en zona insegura

Codigo/InvUsuario.bas
Elimino la restricción hardcodeada de que algunos escudos sí se podían usar con arco y otros no.
Ahora los que usen arco van a usar todos sus escudos balanceados para cada clase.
=> Permito usar escudo y arco

README.md
=> Removed space

Codigo/TCP.bas
=> Actualizo flechas y pociones newbies

Codigo/Protocol_GmCommands.bas
- Removed uptime server in command as is repeated with the command /uptime
- Added restriction only for gms to see qty only
=> /online command only for gms

Codigo/CharacterPersistence.bas, Codigo/Database_Queries.bas
This pull request includes changes to dynamically determine the inventory slot limit and to dynamically build and truncate the inventory query based on the user's type. The modifications improve the flexibility and efficiency of the code.
Dynamic Inventory Slot Limit:
* [`Codigo/CharacterPersistence.bas`](diffhunk://#diff-a150242508384727509fd46f3c7da29f276070fe3b13aae000eb6f0eb8ebfce1L589-R621): Updated `SaveCharacterDB` to dynamically determine the inventory slot limit based on the user's type and adjust the `Params` array accordingly.
Dynamic Query Construction:
* [`Codigo/Database_Queries.bas`](diffhunk://#diff-ead2ded658afad950352e65b036a6d2ed31c6f6513da6b6cdb49959d4e75c1a8R409): Modified `ConstruirQuery_GuardarPersonaje` to use `MAX_INVENTORY_SLOTS` for building the initial …
=> Character Inventory Save improvements.

Codigo/Protocol_GmCommands.bas
Id para el server y cliente Español e Ingles
=> Localization to English

Codigo/Acciones.bas, Codigo/Admin.bas, Codigo/Comercio.bas, Codigo/GameLogic.bas, Codigo/ModShopAO20.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol.bas, Codigo/SistemaCombate.bas, Codigo/Trabajo.bas
se pasan mensajes WriteConsoleMsg a WriteLocaleMsg
con sus traducciones Para el cliente.
se agregan Nuevos Msgxxx= en español e ingles
=> Msg nuevos

Codigo/Logging.bas
Intento cambiar el numero de Eventos
=> Cambio Num De Eventos

Codigo/Logging.bas
This reverts commit b5341695764317ea8f281de9ef802f6a4154c1d5, reversing changes made to 8588b57e4aadba314dc90c0e1e3b153f1fd13342.
=> Revert "Merge pull request #691 from ao-org/NewReportEvent"

Codigo/Logging.bas
Agregamos Evento20 como numero de Evento
=> Agrego Evento20

RegistrarEvento.bat
Este BAT registra el evento 20 en el Event Viewer.
=> Crear Evento ID20

Codigo/InvUsuario.bas, Codigo/modHechizos.bas
This pull request includes changes to the `TieneObjEnInv` function in the `Codigo/InvUsuario.bas` file to improve the handling of inventory slots based on user type and to enhance code readability.
Improvements to inventory slot handling and code readability:
* [`Codigo/InvUsuario.bas`](diffhunk://#diff-03be7c9b977a51a8935e8a8503f9ba726e2fe4b70b80996ad1cf4d6dbe2e50b8L34-L68): Added variables `maxItemsInventory` and `currentObjIndex` to manage inventory slots and object indices.
* [`Codigo/InvUsuario.bas`](diffhunk://#diff-03be7c9b977a51a8935e8a8503f9ba726e2fe4b70b80996ad1cf4d6dbe2e50b8L34-L68): Introduced a `Select Case` statement to determine the number of inventory slots based on the user type (`tLeyenda`, `tHeroe`, or default).
* …
=> Added logic to validate max qty items in inventory

Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/General.bas, Codigo/InvUsuario.bas, Codigo/MODULO_NPCs.bas, Codigo/ModInvasion.bas, Codigo/ModQuest.bas, Codigo/Modulo_InventANDobj.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol.bas, Codigo/Protocol_GmCommands.bas, Codigo/Protocol_Writes.bas, Codigo/ServerConfig.cls, Codigo/SistemaCombate.bas, Codigo/Trabajo.bas, Codigo/frmMain.frm, Codigo/frmServidor.frm, Codigo/modTime.bas, Server.VBP
This pull request includes a minor change to the `Codigo/General.bas` file. The change modifies the `EstadoGlobal` variable assignment in the `Sub Main()` function and adds a TODO comment to indicate that the variable should be added to the `Server.ini` or `Configuracion.ini` file.
Change details:
* [`Codigo/General.bas`](diffhunk://#diff-af45ab886061fad467a88a30b8965a1dcd97721fc86f9e0b139e2781dad878fcL677-R678): Changed the assignment of `EstadoGlobal` from `False` to `True` in the `Sub Main()` function and added a TODO comment to add the variable to `Server.ini` or `Configuracion.ini`.
=> Enabled by default the global chat

Codigo/InvUsuario.bas, Codigo/Protocol_Writes.bas
Replaced the old function with a new one called get_object_amount_from_inventory
=> Fixed inventory function CantidadObjEnInv

Codigo/Protocol_GmCommands.bas, Codigo/frmMain.frm
Changes required to shutdown the server automatically
Update frmMain.frm
=> Implemented remote shutdown

Codigo/Protocol.bas
Fixes:
This pull request includes a critical update to the `Codigo/Protocol.bas` file, focusing on improving the handling of user references and ensuring the robustness of user index validation. The changes introduce additional checks to prevent out-of-bounds errors and enhance error messaging.
Key changes include:
Validation improvements:
* Added a check to ensure that the target index is within the bounds of the `UserList` array before accessing it.
Error handling enhancements:
* Introduced error messages for invalid user references and out-of-bounds indices to provide clearer feedback to users.
These changes help to prevent potential runtime errors and improve the overall reliability of the user trading functionality.
=> Fixed Subscript out of range in HandleResponderPregunta

Codigo/Logging.bas, Codigo/Protocol.bas, Codigo/clsNetReader.cls, Codigo/clsNetWriter.cls, Codigo/frmMain.frm, Codigo/modDPlayServer.bas, Codigo/modNetwork.bas
Improved error handling
Improved flow CreatePlayer/DestroyPlayer
=> DPlay: various fixes

Codigo/Protocol.bas, Codigo/Protocol_Writes.bas, Codigo/clsNetReader.cls, Codigo/clsNetWriter.cls
1. Implemented Write/Read/SafeArrayInt8
2. Redim oMsg before calling DPlay to make sure we don't send additional data.
3. Removed dodgy method HandleSendPosMovimiento which was using ReadString16 incorrecttly.
=> Various DPlay fixes

Codigo/SistemaCombate.bas
Este cambio sube la probabilidad de apuñalar del Asesino contra los npcs
=> Probabilidad de apuñalar asesino

Codigo/Protocol.bas
Todos pueden tirar items en altamar
=> Piratas pueden tirar items en altamar

Codigo/Protocol_Writes.bas
Envía la clase requerida a través de RequiredClass en quest.dat
=> Envio de RequiredClass (quest)

Codigo/modNetwork.bas
=> DPLAY: removed DPNOP_SYNC

Codigo/InvUsuario.bas
Al igual que cuando se gana experiencia, con este cambio se muestra arriba del personaje, en color dorado, la cantidad de oro que se agarra del suelo.
=> Oro recogido se muestra en pantalla

Codigo/Declares.bas, Codigo/ModQuest.bas, Codigo/Protocol.bas, Codigo/Protocol_Writes.bas
Agrego propiedad LimitLevel para las quest  y también envio esos datos al cliente para poder mostrarlos como requisito en caso de ser necesario.
=> Propiedad nueva en quest: LimitLevel

Codigo/ServerConfig.cls, Codigo/Trabajo.bas, Configuracion.ini
Al eliminar el vigilante pongo un NPC en su lugar.
=> Remplazo de lo que seria un vigilante

Codigo/Protocol.bas
Paso a Public HandleRomperCania
permito eliminar del slot 24 el item
=> Paso a Public HandleRomperCania y permito eliminar del slot 24 el item

Codigo/Protocol.bas, Codigo/Trabajo.bas
elimino romper linea de pesca con el calamar
revierto a Private Sub HandleRomperCania
paso de Public a Private
=> Elimino romper linea de pesca

Codigo/ModQuest.bas, Codigo/Protocol_GmCommands.bas
Convert WriteChatOverHead messages to localized format (WriteLocaleChatOverHead)
=> Convert WriteChatOverHead messages to localized format (WriteLocaleChatOverHead)

Codigo/Acciones.bas, Codigo/GameLogic.bas, Codigo/InvUsuario.bas, Codigo/ModFacciones.bas, Codigo/ModQuest.bas, Codigo/Protocol.bas, Codigo/Protocol_GmCommands.bas
Refactor chat messages to use localized IDs
=> Refactor chat messages to use localized IDs

Codigo/ModSubasta.bas, Codigo/Protocol.bas
Refactor_Chat_Messages_to_use_localized_IDs
=> Refactor_Chat_Messages_to_use_localized_IDs

Codigo/ModGrupos.bas, Codigo/ServerConfig.cls, Codigo/SistemaCombate.bas, Configuracion.ini
- Si el líder del grupo no se encuentra en el mapa donde el npc es atacado, la experiencia que corresponde al líder se pierde
- La diferencia para crear un grupo es de 4 niveles
=> La experiencia del lider del grupo se divide siempre

Codigo/Protocol_GmCommands.bas, Codigo/Trabajo.bas
English translations of commands and server information
=> English translations of commands and server information

Codigo/General.bas, Codigo/clsIniManager.cls
I delete unnecessary commented lines
=> I delete unnecessary commented lines

Codigo/Admin.bas, Codigo/GameLogic.bas, Codigo/General.bas, Codigo/InvUsuario.bas, Codigo/MODULO_NPCs.bas, Codigo/ModEventos.bas, Codigo/ModRetos.bas, Codigo/ModTesoros.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol.bas, Codigo/Protocol_GmCommands.bas, Codigo/clsCaptura.cls, Codigo/frmAdmin.frm, Codigo/frmMain.frm, Codigo/mdlCOmercioConUsuario.bas, Codigo/modBanco.bas, Codigo/modGuilds.bas
ID Server remplazo PrepareMessageConsoleMsg x PrepareMessageLocaleMsg
=> ID Server remplazo PrepareMessageConsoleMsg x PrepareMessageLocaleMsg

Codigo/Protocol_GmCommands.bas
=> Update Protocol_GmCommands.bas reverse the line of workers

Codigo/InvUsuario.bas, Codigo/Protocol.bas, Codigo/ScenarioDeathMatch.cls, Codigo/Scenearios/NavalBoarding.cls
=> IDs DeathMatch

Codigo/Modulo_UsUaRiOs.bas, Codigo/Penas.bas, Codigo/Protocol_GmCommands.bas, Codigo/TCP.bas, Codigo/Trabajo.bas, Codigo/clsCaptura.cls, Codigo/frmMain.frm, Codigo/modHechizos.bas, Codigo/modNetwork.bas
=> New translations

Codigo/Protocol.bas, Codigo/Protocol_GmCommands.bas, Codigo/ScenarioDeathMatch.cls, Codigo/ScenarioKillNpc.cls, Codigo/Scenearios/NavalBoarding.cls, Codigo/ScoreBoard.cls, Codigo/frmMain.frm, Codigo/modGuilds.bas
=> new DeathMatch IDs

Codigo/Protocol_GmCommands.bas
This reverts commit 8a8a6eb7aa037ee8653b854b9d3aabe87cfb19ab.
=> Revert "New translations (#794)"

Codigo/AI_NPC.bas, Codigo/Consts.bas, Codigo/Declares.bas, Codigo/GameLogic.bas, Codigo/MODULO_NPCs.bas, Codigo/PathFinding.bas, Server.VBP
* NPCs used to get stucked behind a wall and users could kill them using range weapons or spells. This patch fixes the problem by making the NPCs capable of finding a path to the agressor.
* Simplified max distance check in pathfinding by removing .pathFindingInfo.Inteligencia and handling all only with RangoVision
*Increased RANGO_VISION_X Y by 10 to make NPCs chase users even when they go out of the rendered screen
=> Improved AI: NPCs are slightly more inteligent

Codigo/CharacterPersistence.bas, Codigo/Declares.bas, Codigo/InvUsuario.bas
Nuevas mascaras eliminan cabezas
=> Nuevas mascaras

Codigo/Consts.bas
Bajo a 13 15 la visión de los NPCs
=> Bajo a 13 15 la visión de los NPCs

Codigo/PathFinding.bas, Codigo/ServerConfig.cls, Configuracion.ini
In Configuracion.ini we can change the max number of steps for pathfinding with the value NPCMaxStepsPathFinding=500
=> Make pathfinding max steps configurable

Codigo/AI_NPC.bas, Codigo/Consts.bas, Codigo/Declares.bas, Codigo/ServerConfig.cls, Configuracion.ini
Impose a ceiling of 50 for NPCMaxVisionRange
=> NPCMaxVisionRange configurable from file

Codigo/Consts.bas, Codigo/SistemaCombate.bas
- Implemento efecto para el apuñalar cuando un usuario recibe apuñalamiento de otro usuario.
- Implemento efecto de sangre cuando un usuario recibe daño por golpe de otro usuario.
=> Implemento fxs para golpe y apuñalar

Codigo/Protocol_GmCommands.bas
Cambio el nombre en la llamada al sub. Se me paso esta linea y al compilar daba error.
=> Cambio nombre a ingles

Codigo/InvUsuario.bas
This pull request refactors potion consumption logic in the `InvUsuario.bas` file to improve readability and maintainability. The most significant change is the extraction of the potion-free zone check into a new helper function, `IsPotionFreeZone`, which simplifies the main logic and centralizes zone-related conditions.
* **Extraction of potion-free zone logic into a helper function**: Introduced a new private function, `IsPotionFreeZone`, which consolidates all conditions for determining whether a user is in a zone where potions are not consumed. This includes checks for trigger zones, subscription tiers, tournament zones, special zones, and training zones.
* **Simplified main potion consumption logic**: Replaced the inline zone-related conditions in the `Sub UseInvItem` method with a …
=> Add IsPotionFreeZone and add events map to free zone potions

Codigo/Modulo_UsUaRiOs.bas
"The welcome greeting was modified to be consistent in all cases, providing a clear and coherent message."
=> Update welcome greeting

Codigo/frmMain.frm
"The server now sends the NPC number instead of the name, allowing the client to use the correct language when displaying the NPC name."
=> NPC names by ID

Codigo/General.bas, Codigo/PacketId.bas, Codigo/Protocol.bas, Codigo/Protocol_Writes.bas, Codigo/frmMain.frm
Removed unused messages
eForceUpdate
eRequestTelemetry
eSendTelemetry
=> Cleanup protocol's messages

Codigo/PacketId.bas, Codigo/Protocol.bas, Codigo/Protocol_Writes.bas
Implemento sistema de chat faccionario por consola
Con esta implementación, los usuarios pertenecientes a una facción podrán comunicarse entre ellos a través del comando /FMSG.
Necesario aceptar PR en cliente
=> Feat: Chat faccionario

Codigo/InvUsuario.bas
adding the arena of lindos as a zone where no potions will be consumed
=> adding the arena of lindos as a zone where no potions will be consumed

Codigo/Protocol.bas
=> Fix IDs control macros

Codigo/ModGrupos.bas, Codigo/ServerConfig.cls, Codigo/SistemaCombate.bas, Configuracion.ini
-added +1 level to party lvl delta for people that have 15-(Charisma/2) in leadership
-added configurable bonus (actually 1%) to bonus exp for all the member in the party that have 15-(Charisma/2) in leadership
=> leadership bonus

Codigo/ModGrupos.bas, Codigo/ServerConfig.cls, Codigo/SistemaCombate.bas, Configuracion.ini
Reverts ao-org/argentum-online-server#852
Revierto por que no compila el server.
> [re20-server-master] $ cmd.exe /C " "C:\Program Files (x86)\Microsoft Visual Studio\VB98\vb6.exe" /make /outdir C:\jenkins-agent\workspace\re20-server-master /d UsarQueSocket=1:ConUpTime=1:AntiExternos=0:Lac=1:DEBUGGING=1:PYMMO=1:UNLOCK_CPU=1:DIRECT_PLAY=0 /out C:\jenkins-agent\workspace\re20-server-master\vb6build17600516935129591507.log C:\jenkins-agent\workspace\re20-server-master\Server.VBP " && exit %%ERRORLEVEL%%
> 
> Compile Error in File 'C:\jenkins-agent\workspace\re20-server-master\Codigo\SistemaCombate.bas', Line 1895 : Syntax error
> Build of 'server.exe' failed.
=> Revert "leadership bonus"

Codigo/Protocol.bas
- Replaced unsafe Err.Raise calls with TraceError for both:
- Unhandled packet IDs (Case Else)
- Unexpected trailing bytes in packet
- Added explicit admin logging and GM notifications for better visibility
- Ensured invalid packets result in connection kick and early exit
- Set HandleIncomingData = True at the end of successful processing
- Simplified logic for clarity and consistency with existing codebase
=> Refactored handling of malformed packets

Codigo/Declares.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/PacketId.bas, Codigo/Protocol.bas, Codigo/Protocol_Writes.bas, Codigo/SistemaCombate.bas
Add package and events for legionary segure in server
=> Legionary Secure

Codigo/Acciones.bas, Codigo/Comercio.bas, Codigo/GameLogic.bas, Codigo/Protocol_Writes.bas
=> FIX LOCALIZE WAV

Codigo/Declares.bas, Codigo/Protocol.bas
-Added excepcion for gold slot (previously added sanity check for slots didn't take into consideration that gold is harcoded 200)
=> fix_DropGold

Codigo/CharacterPersistence.bas, Codigo/InvUsuario.bas
-Fixed a not intended behaviour where faction people logging in insecure zones got their armor item unequiped
=> fix_UnequippedFactionArmorOnSpawn

ScriptsDB/20250908-01-update descriptions.sql
Force set descriptions to null to match client change https://github.com/ao-org/argentum-online-client/pull/580
=> fix_DescriptionsSetToNull

Codigo/SistemaCombate.bas
-Fixed my old fork repo artifact where https://github.com/ao-org/argentum-online-server/commit/c7ff52864ac4b3dd6cda5d1a3e2f2dd3a5b4fff8 was not re-reverted
=> fix_ForkArtifacts

Codigo/Protocol.bas, Codigo/Protocol_Writes.bas
Fix a discoordination protocol bug who causes a suscript out of range.
=> Fix protocol bug

Codigo/Modulo_UsUaRiOs.bas
Elimino el envío de mensaje duplicado que se enviaba al usuario al subir un skill naturalmente
=> Elimino mensaje duplicado en SubirSkill
