Codigo/TCP.bas, Codigo/modHechizos.bas, Codigo/modNetwork.bas
when if the code call player clear before the disconnection takes place the disconnection may fail to clear the connection id for the player slot
when that happens the timeout code might step on a unused slot with a random .ConnId and try to kick it
let say player on userSlot5 has connectionId = 4
if he disconnect and we dont clear the slot containts conId=4
after that if someone reuse the connectionId 4 to UserSlot=6
on next timeout tick the code will find the UserSlot 5 with valid ConId and and very long timestamp and kick connection 4
this prevent anyone connecting with that connection until server restart or someone login to the same slot fixing the timestamp and connection values
=> Clear connection reference

Codigo/FileIO.bas, Codigo/General.bas, Codigo/UnitClient.bas, Codigo/Unit_Protocol_Writes.bas
Now it can reconnect and run a sequence of tests simulating client requests
Added handler for unit test
Added handled for ServerPacketID.ErrorMsg in the unit test
The server closed the socket because we were loading only 10 maps and the PC was in map 34 (invalid map)
=> Unit testing client

Codigo/Declares.bas
RequiredQuest variable was originally byte and that limits our posibility to develop quests to 255.
=> FacudeArghal - Declares datatype

Codigo/TCP.bas
Cambios en el Equipamiento Inicial
=> Cambios en el Equipamiento Inicial

Codigo/FileIO.bas
La rutina InitAreas se estaba llamando posterior a la carga de los mapas.
Todos los NPCs creados durante la carga de mapas tenían las areas incorrectas.
=> Fixes #451 NPCs invisibles

Codigo/General.bas
Si hay un proceso en ejecución cuyo nombre incluye “[nombre del ejecutable].exe”, el chequeo que hace para ver si ya hay una instancia de la app falla. Ahora chequea que el nombre del proceso sea el mismo.
=> Fix chequeo de multiples instancias

Codigo/CharacterPersistence.bas, Codigo/frmMain.frm
Antes:
Si en objs.dat tu NumObjs=3675, pero en la DB tenés una fila con item_id=4000 esas funciones crashean y el personaje no carga.
Ahora:
Si pasa eso, ignora el item_id de esa fila y no lo carga, hace como si no tuvieses ningún item en ese slot.
=> Add ObjData bounds checking in LoadCharacterInventory & LoadCharacterBank

Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/GameLogic.bas, Codigo/ModGrupos.bas
Si un usuario no pertenece a un grupo, no va a poder entrar al mapa.
Si un usuario sale del grupo o es expulsado del mismo estando en un mapa con esta restricción y dicho mapa tiene coordenadas de salida, este será teletransportado a la misma.
Esto se debe usar en conjunto con esto:
https://github.com/ao-org/argentum20-worldeditor/pull/2
Closes #455
=> Nueva restriccion de mapa solo para grupos

Codigo/ModGrupos.bas, Codigo/Protocol.bas, Codigo/TCP.bas
Arreglo error introducido en PR #503.
Producía que al salir de grupo en algunos mapas te llevaba afuera (aún sin tener habilitado que sea un mapa solo mapa grupos).
También arreglo un poco el sistema, ya que había casos en los que el lider quedaba dentro igual.
También arreglo el invitar a grupo, que no funcionaba a la primera (faltaba un LookAtTile).
Queda mucho código repetido en el código que finaliza el grupo al salir los miembros, pero lo dejo para mejorar más adelante.
=> Fix abandonar party te saca del mapa

Codigo/AI_NPC.bas, Codigo/Admin.bas, Codigo/Declares.bas, Codigo/EffectProvoked.cls, Codigo/FileIO.bas, Codigo/FrmInterv.frm, Codigo/GameLogic.bas, Codigo/MODULO_NPCs.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol.bas, Codigo/SistemaCombate.bas, Codigo/clsIniManager.cls, intervalos.ini
Fixes #514
Se elimina el chequeo de distancia para ser "dueño" de un NPC.
Tenía un bug fácil de arreglar pero charlando con los game master pensamos que sería mejor otra estrategia.
Ahora es por tiempo: 10 segundos (por defecto) desde el último ataque.
Esto es configurable desde intervalos.ini Igualmente al irte del rango de visión del NPC dejás de ser el dueño. 
Arreglé otro errorcito que si pasabas por al lado de un NPC que tenía dueño, ignoraba todas las validaciones y te golpeaba igual.
=> Fix seguro NPC

Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol_Writes.bas
Fix #465 y fix #518
Varios cambios acá. Principalmente las validaciones para enviar los personajes invisibles al cliente no eran las mismas en los dos lados que se usan. Queda pendiente reescribirlo mejor esto algún día.
Si un usuario invisible se alejaba de otro usuario, debe borrarse el char en el cliente. Esto no funcionaba.
Faltaba también controlar el caso que un usuario se mueva cerca de otro estando invisible. Es necesario mandar paquetes al cliente acá para que no se quede bloqueado en una posición.
Esto va mergeado con un PR en el cliente que se llama igual. Mergear ambos a la vez ya que hay cambios de paquetes.
=> Fix invisibilidad

Codigo/EffectProvoked.cls, Codigo/MODULO_NPCs.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/SistemaCombate.bas
La condición estaba invertida. Producía que los NPC no ataquen a otros usuarios cuando están inmovilizados.
=> Fix error introducido en PR de seguro NPC

Codigo/Declares.bas, Codigo/GameLogic.bas, Codigo/General.bas, Codigo/InvUsuario.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol.bas, Codigo/ScenarioDeathMatch.cls, Codigo/ScenarioKillNpc.cls, Codigo/Scenearios/NavalBoarding.cls, Codigo/SistemaCombate.bas, Codigo/TCP.bas, Codigo/Trabajo.bas, Codigo/modHechizos.bas, Codigo/modSendData.bas
Para evitar carteles y fxs saltarines:
- Alargo el tiempo de animacion en invisible de dialogos y fxs
- Agrego timer para dialogos de clan
Fix en merge anterior los gms dejaron de ver los users invisibles
Creo que también fixee que los usuarios puedan patear gms? Esto hay que probarlo
=> Fix invi 2

Codigo/CharacterPersistence.bas
Estaba mal el chequeo del límite de objetos y borraba el item
Fixes #519
=> Fix pieles

Codigo/ModAreas.bas, Codigo/Protocol_Writes.bas
Estaba enviando las coordenadas del notificado en vez del usuario invisible
=> Fix meditar invi

git_ignore_case.sh
This script aims to automate the tedious task of filtering out case-only changes made by the VB6 IDE, allowing you to focus on the meaningful changes in your git diff output.
Key Enhancements:
- Function Usage: Encapsulated the processing logic into a process_file function to avoid code duplication and improve readability.
- Case Normalization: Used awk to convert both the original and the modified file contents to lowercase before diffing. This approach helps to ignore case-only differences.
- Conditional Patch Application: The script now checks if the patch file ($PATCHFILE) is non-empty before applying it. This ensures that changes are only made if there are actual differences beyond case changes.
- File Handling: Improved the handling of file paths in the script to ensure it works …
=> Applied improvements for unwanted diff from VB6 IDE

Codigo/modNetwork.bas
We have reports that the game was broken with these kind of error for sending a boolean instead of string.
Fixes
=> Fixed type parameter in Server.Kick and added text description for all of them

Codigo/Modulo_UsUaRiOs.bas, Codigo/SistemaCombate.bas
Con esta modificación hago que los personajes ocultos se vuelvan visibles cuando realizan un golpe melee a otro usuario. Esto arregla el problema del bandido que podía caminar y pegar oculto sin que se le vaya el ocultar al hitear a alguien. Esto no aplica a tirar hechizos, ni a proyectiles, ni a pegarle a NPCs.
=> Remuevo ocultar al atacar melee

Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/General.bas, Codigo/LocaleDef.bas, Codigo/frmMain.frm
Reemplazo el viaje en barco de nix/arghal a forgat y viceversa que hay actualmente por:
- 3 eventos que manejan 3 barcos independientes
- un barco va de forgat a nix
- otro va de nix a arghal
- otro va de arghal a forgat
Esto es beneficioso por varios motivos:
- Acorta mucho las distancias, los usuarios podrán tomarse el barco para viajar al precio del boleto rodeando todo el mundo
- Los 3 barcos son independientes, usan mapas distintos por lo que no se deben esperar entre si
- Simplifiqué la lógica que tenían los viajes, es más simple de entender y en todo caso quedan herramientas para complejizar a gusto
=> Nuevos viajes en barco

Codigo/InvUsuario.bas
Cuando un personaje pasa a nivel 13 y deja de ser Newbie es teletransportado a la Isla de la Fortuna donde obtiene algo de equipamiento básico. Este cambio es para que cualquier personaje que pase a 13 sin importar el mapa pueda ir a la isla. Antes solo te enviaba a la isla si pasabas en Dungeon Newbie.
=> Envío a Isla de la Fortuna sin importar el mapa

Codigo/SistemaCombate.bas
Cambios implementados: El bandido ahora pega críticos y desequipa con nudillos.
- Subo la probabilidad de pegar críticos a 0.25 por la cantidad de skills en combate sin armas
- Saco el bonus de probabilidad de meter crítico a NPCs
- Ahora el bandido puede desequipar desde nivel 1, pero la prob. aumenta con el skill en combate sin armas
- Bajo la probabilidad de desequipar a 0.2 por la cantidad de skills en combate sin armas (con el feature toggle activado)
- Separo la condición para meter crítico y para desequipar en código
=> Actualizo crítico y desequipar del bandido

Codigo/Trabajo.bas
Con este cambio permito que los que estén invisibles u ocultos puedan montar y pierdan el ocultar/invisibilidad. Esto hace más dinámico el juego ya que evita tener que esperar a que se te vaya el ocultar o el invi, o evita que apreten f12 con tal objetivo.
=> Montar oculto te hace visible

Codigo/ModCola.cls
Fixed bug reported in:
https://github.com/ao-org/argentum-online-server/issues/611
=> [ISSUE-611] Fixed GM requests removal

Codigo/Admin.bas, Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/Trabajo.bas
- Ahora se puede pescar en zona insegura con caña, la red sigue sirviendo solo en las áreas de pesca.
- Ahora se puede poner el porcentaje de reducción de pesca en zona segura respecto a insegura desde el dateo de balance.dat. Aquí se puede poner 10% y queda ínfima.
- Ahora se puede definir la bonificación que dan las cañas en el dateo de pesca.dat, antes estaba hardcodeado. Estos valores dependen del Power que tengan en el obj.dat.
- Ahora la pesca en zona segura NO sube skills en pesca.
- Saqué la bonificación de clase para trabajadores ya que solo pescan trabajadores
- Saqué la restricción hardcodeada de puntos de pesca para usar la red, ya que se restringe por nivel en el obj.dat
- Documenté un poco el código
=> Actualizo código de pesca

RegistrarAurora.bat
Se crea archivo BAT para auto-registrar la DLL AuroraNetwork en la carpeta donde esté instalado el server, si no se ejecuta como Administrador el BAT alerta al usuario y lo corre como Administrador, evitando asi cualquier tipo de incoveniente con la registración del mismo.
=> Creado Archivo BAT para registrar AuroraNetwork

Codigo/InvUsuario.bas
Agregamos una linea del codigo del server para que en las arenas de los sotanos patreon no se consuman las pociones rojas y azules.
=> Arena de sotano Patreon

Codigo/InvUsuario.bas, Codigo/Modulo_UsUaRiOs.bas
Eliminamos items newbies de la boveda cuando se deja de ser newbie.
Si moris en la arena no suma muerte, si matas en la arena no suma kill.
Fix /est, agregamos la call para solicitar la info de los creditos antes de mostrarlos.
=> Arenas, /est e items nws en boveda.

Codigo/Acciones.bas, Codigo/ModCaptura.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/clsCaptura.cls
1.Mejoramos la informacion de la puerta del ducto al intentar abrirla.
2.Realizamos varios cambios en el evento de captura a la bandera.
-Tiempos de ejecucion del evento
-Usuarios entre equipos no se pueden atacar
-Sistema de recompensa en oro por ganar el evento.
=> Captura a la bandera e Info de la puerta del ducto o drenaje.

Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/modHechizos.bas
Agreamos el requisito de tener una flauta para usar el hechizo de invocar mascotas
=> Flautas para invocar

Codigo/Protocol_GmCommands.bas
Se cambia el valor de apuesta máxima de 10.000 monedas a 5.000 monedas
Se ajusta el porcentaje de probabilidades de ganar porque estaba muy elevado
=> Actualización del codigo del Apostador

Codigo/Protocol.bas, Codigo/modGuilds.bas
Actualizamos los requisitos necesarios para fundar un clan dentro de Argentum Online:
- Reducción de Nivel: ahora se puede fundar a partir de Nivel 23 (solicitaba ser Nivel 25 o más)
- Aumento de Skills: ahora es necesario tener 50 puntos en Liderazgo para fundar un clan (solicitaba 35 puntos en Liderazgo)
=> Requisitos para Fundar un Clan

Codigo/CharacterPersistence.bas
This pull request includes a significant change to the `SaveCharacterDB` method in the `Codigo/CharacterPersistence.bas` file. The change simplifies the inventory slot handling by removing the conditional logic based on user type and directly using a fixed maximum inventory slot limit.
* Removed conditional logic that determined inventory slot limits based on user type (`tLeyenda`, `tHeroe`, etc.) and replaced it with a fixed maximum inventory slot limit (`MAX_INVENTORY_SLOTS`).
* Adjusted the loop to iterate over the fixed maximum inventory slots and updated the parameters accordingly.
NOTE: This will delete all the items for subscriptions that are removed in the special inventory slots.
=> Reverted Persistance of Character's inventory

Codigo/Declares.bas
This pull request includes changes to the inventory slot constants in the `Codigo/Declares.bas` file. The changes adjust the number of slots available in different types of inventories to ensure consistency and balance.
Changes to inventory slot constants:
* [`Codigo/Declares.bas`](diffhunk://#diff-9682fb78ca936b593db35585cec8ff7c38ac045a2cc5f5f6b140d03aa0488813L809-R815): Reduced `MAX_INVENTORY_SLOTS` from 42 to 24.
* [`Codigo/Declares.bas`](diffhunk://#diff-9682fb78ca936b593db35585cec8ff7c38ac045a2cc5f5f6b140d03aa0488813L809-R815): Reduced `MAX_USERINVENTORY_HERO_SLOTS` from 31 to 24.
=> Premium slots temporary disabled, all characters have the same qty slots

Codigo/Acciones.bas, Codigo/Comercio.bas, Codigo/GameLogic.bas, Codigo/General.bas, Codigo/InvUsuario.bas, Codigo/MODULO_NPCs.bas, Codigo/ModQuest.bas, Codigo/ModRetos.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol.bas, Codigo/Protocol_GmCommands.bas, Codigo/SistemaCombate.bas, Codigo/Trabajo.bas, Codigo/modCrafteos.bas, Codigo/modHechizos.bas, Server.VBP
Primeros mensajes pasados a ID
Update modHechizos.bas
=>  Localizacion del server: agregamos nuevos ID para msg al cliente

Codigo/MODULO_NPCs.bas
Make sure the number of items in the inventory don't exceed the MAX. If this is the case we print a warning and clamp the value.
=> Saninty check when loading NPCs

Codigo/General.bas, Codigo/Modulo_UsUaRiOs.bas, Codigo/Protocol_Writes.bas, Codigo/TCP.bas, Codigo/UnitClient.bas, Codigo/UnitTesting.bas, Codigo/Unit_Protocol_Writes.bas, Codigo/clsNetReader.cls, Codigo/clsNetWriter.cls, Codigo/frmMain.frm, Codigo/modNetwork.bas, Codigo/modSendData.bas
Added clsNetWriter in modSendData.
The server can now handle incoming messages from the client and replay.
Various fixes in clsNetWriter and clsNetReader: the sizes of some types was incorrect. Also DP will crash is passed a null string, I implemented a workaround for this.
=> Various fixes for DirectPlay

Codigo/Trabajo.bas
Fixes:
9 - Error number: 9 | Description: Subscript out of range
Component: Trabajo.AlquimistaConstruirItem | Line number: 104
This pull request introduces a new subroutine, `AlquimistaConstruirItem`, to the `Codigo/Trabajo.bas` file. This subroutine is designed to handle the construction of items by an alchemist character in the game. The most important changes include the validation of array bounds, the main logic for item construction, and error handling.
Validation and Error Handling:
* Added array bounds validation for `UserIndex`, `ItemIndex`, and the equipped tool index to ensure they are within valid ranges. If any of these indices are out of range, a specific error is raised.
* Implemented error handling with a label `AlquimistaConstruirItem_Err` to capture and log errors, …
=> Fix AlquimistaConstruirItem Array out of bounds

Codigo/Trabajo.bas
This pull request includes changes to improve error handling in the `AlquimistaConstruirItem` method in the `Codigo/Trabajo.bas` file. The changes replace `Err.Raise` statements with calls to a `TraceError` method and ensure that the subroutine exits gracefully when an error is encountered.
Improvements to error handling:
* Replaced `Err.Raise` statements with `TraceError` calls to log errors and exit the subroutine when `UserIndex`, `ItemIndex`, or `HerramientaEqpObjIndex` are out of range.
* Added a `Resume Next` statement after logging errors in the `AlquimistaConstruirItem_Err` section to allow execution to continue.
=> Improved function AlquimistaConstruirItem

Codigo/MODULO_NPCs.bas, Codigo/SistemaCombate.bas
Cambio de color del mensaje en consola: "Has matado a la criatura"
Cambio de color del mensaje en consola del golpe critico (atacante y victima), ahora se muestra del mismo color que el de apuñalar.
=> Cambio de color en mensajes

Codigo/Declares.bas, Codigo/MODULO_NPCs.bas
To make an NPC attackable by everyone indistinctly (citizens can share the NPC with other citizens and also criminals) we have to add 
AttackableByEveryone=1
to the end of the NPC configuration in npcs.dat
Example (see last line):
[NPC522] 'Goblin
Name=Goblin
Head=0
Body=4116
Heading=3
Movement=2
Alineacion=0
Attackable=1
Comercia=0
Hostile=1
GiveEXP=160
MinHP=200
MaxHP=200
MaxHIT=25
MinHIT=15
DEF=0
PoderAtaque=75
PoderEvasion=40
NumQuiza=1
QuizaDropea1=1278-1
QuizaProb=10
NumDropQuest=1
DropQuest1=84-2159-1-3
Humanoide=0
NPCLVL=9
MagicResistance=23
MagicDef=0
AttackableByEveryone=1
=> Neutral NPCs. Can be attacked by everyone

Codigo/modHechizos.bas
Se elimina del código del servidor el condicional que permite 1 sola invocación de los siguientes NPCs:
- FUEGO FATUO
- ELEMENTAL DE VIENTO
- ELEMENTAL DE FUEGO
Con este cambio, se pueden invocar nuevamente hasta 3 NPCs, simulando al comportamiento del hechizo "Elemental de Agua" / "Elemental de Tierra"
=> Condicional sobre Invocación

Codigo/ServerConfig.cls, Codigo/clsNetWriter.cls, Codigo/modNetwork.bas, Configuracion.ini
Also disabled enumeration DPNSESSION_NODPNSVR
This lets us tune DPLAY settings with config file without having to recompile
=> DPLAY: load DPN_CAPS  from config file

Codigo/clsClan.cls
Se corrigió un problema en la función GetMemberList que causaba que solo se mostrara el líder del clan después de expulsar a un miembro.
Causa del bug:
La asignación de GetMemberList = Members se realizaba dentro del bucle For, lo que provocaba una salida prematura de la función debido a un Exit Function dentro de la primera iteración.
Solución implementada:
Se movió la asignación de GetMemberList = Members fuera del bucle para garantizar que todos los miembros sean agregados correctamente antes de devolver el resultado.
Se eliminó el Exit Function dentro del bucle para permitir que el código complete la iteración correctamente.
=> Corrección de bug en la lista de miembros del clan

Codigo/Protocol_Writes.bas
Elimino linea innecesaria que causaba bug visual en la ventana frmQuest del cliente
=> Do not send LimitLevel in  WriteQuestDetails

Codigo/SistemaCombate.bas
- Cuando un usuario ataca a otro usuario ya no se muestra el mensaje "El ser es demasiado poderoso" 
- Ahora los admins y gms NO pueden ser atacados por usuarios
=> Mejoras en restricciones de ataque

Codigo/modGuilds.bas
- El mensaje "Clan> El clan ha ganado XX puntos de experiencia." se envía correctamente a todos los miembros conectados y con ChatCombate activado.
=> Fix: Envío de mensaje de experiencia a miembros del clan

Codigo/Declares.bas, Codigo/MODULO_NPCs.bas, Codigo/Trabajo.bas
- Ahora desde el dateo se puede agregar la propiedad MinLVLDomable a los npcs. Con esta propiedad se puede definir un nivel mínimo requerido para poder domar una criatura.
=> Implementación de MinLVLDomable para npcs

Codigo/ModGrupos.bas
Se reduce a 3 niveles el rango el permitido para crear un grupo; de esta manera, y con un ejemplo sencillo, un personaje nivel 20 podrá armar un grupo con un compañero de nivel 23, pero no con uno de nivel 24
=> Reducción de amplitud de niveles

Codigo/ModGrupos.bas, Codigo/SistemaCombate.bas, Codigo/Trabajo.bas
-Cambio de id en el mensaje "El líder del grupo está demasiado lejos, su experiencia se pierde."
-Agrego id para mensaje de creación de grupo
-Arreglo el envio de mensaje "Debes ser nivel ¬1 o superior para domar esta criatura.", le faltaba el valor
=> Fix en envios de varios mensajes

Codigo/Protocol_GmCommands.bas
Por pedido de Temis, cambio el tipo de fuente a uno mas llamativo para los mensajes en consola vía /RMSG (con la fuente anterior los mensajes se perdían).
=> Cambio de fuente para /RMSG

Documentation/AI_NPC.md, Documentation/AI_NPC.mmd, Documentation/AO20CryptoSysWrapper.md, Documentation/AO20CryptoSysWrapper.mmd, Documentation/API.md, Documentation/Admin.md, Documentation/Admin.mmd, Documentation/CharacterPersistence.md, Documentation/CharacterPersistence.mmd, Documentation/Comercio.md, Documentation/Comercio.mmd, Documentation/Database_Queries.md, Documentation/Database_Queries.mmd, Documentation/EffectsOverTime.md, Documentation/EffectsOverTime.mmd, Documentation/GameLogic.md, Documentation/GameLogic.mmd, Documentation/ProjectOverview.mmd, Documentation/README.md
This update introduces Markdown documentation (.md) and Mermaid component diagrams (.mmd) for a subset of modules in the `Codigo/` directory.
Modules for which I generated documentation (at least .md and in most cases .mmd) include:
- AI_NPC
- AO20CryptoSysWrapper
- API
- Admin
- CharacterPersistence
- Comercio
- Database_Queries
- EffectsOverTime
- GameLogic
A `Documentation/README.md` provides an overview and links to these documents. A `Documentation/ProjectOverview.mmd` offers a high-level component diagram of their interactions.
Note: I encountered some challenges, which prevented me from documenting all modules as initially planned. This update includes the subset I successfully generated.
=> I've added initial module documentation and component diagrams for you.

Codigo/InvUsuario.bas
This pull request refactors the `IsPotionFreeZone` function in `Codigo/InvUsuario.bas` to improve readability and maintainability. The changes include renaming variables for clarity and replacing a hardcoded condition with a `Select Case` statement for better extensibility.
* Renamed the variable `isTournamentZone` to `isHouseZone` to better reflect its purpose, which checks if the current map falls within the house/basement arena range (maps 600–749 with an active trigger). [[1]](diffhunk://#diff-03be7c9b977a51a8935e8a8503f9ba726e2fe4b70b80996ad1cf4d6dbe2e50b8L3242-R3242) [[2]](diffhunk://#diff-03be7c9b977a51a8935e8a8503f9ba726e2fe4b70b80996ad1cf4d6dbe2e50b8L3258-R3274)
* Replaced the hardcoded condition for `isSpecialZone` with a `Select Case` statement, making it easier to add or …
=> Added more maps to Free Potion Zone

Codigo/clsCaptura.cls
Este PR soluciona el inconveniente que generaba la cancelación automatica por falta de jugadores. Los personajes se inscriben por una cantidad de monedas de oro y al no iniciar el evento, los devuelve a la posición desde donde enviaron /PARTICIPAR sin el oro de la inscripción. Con este cambio, si se cancela el evento por falta de jugadores, les devuelve el oro de la inscripción.
=> fix cancelar captura la bandera

Codigo/Protocol_GmCommands.bas
Updates the message that is shown when the user does not have enough gold when trying to enter the arena
Now displaying message id 2040. Requested by @Temis-gt
=> ArenaEntry message update

Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/InvUsuario.bas
Flag name "LeadersOnly". Values 0 or 1.
It's meant to be used with flags "Real" or "Caos".
=> Add flag to restrict object use to faction leaders only

Codigo/SistemaCombate.bas
-ahora la probabilidad de rechazo con escudo utiliza la propiedad porcentaje, que antiguamente solo servia para denotar un escudo "cosmetico" de uno funcional
-teniendo dicha propiedad porcentaje=100 los escudos actuan de manera normal, teniendo un numero menor a 100 y mayor a 1 reducen su porcentaje de efectividad de escudeo 1 a 1 de manera porcentual, es decir que si porcentaje = 95, el esucdo escuda un 5% menos de lo normal
-se mantiene aun asi la funcionalidad de dejar la propiedad = 0 para escudos cosmeticos
=> cambio de probabilidad de rechazo c escudo

Codigo/Protocol.bas
Add validation for unassisted macro usage using SPELL_UNASSISTED_FULGOR
- Replaced hardcoded spell ID (52) with named constant SPELL_UNASSISTED_FULGOR
- Prepared condition for future support of additional unassisted spell IDs
- Improved readability and maintainability by avoiding magic numbers
- This change ensures that only defined spells can trigger the unassisted macro behavior
Closes issue #XXX (if applicable)
=> Add validation for unassisted macro usage using SPELL_UNASSISTED_FULGOR

Codigo/Protocol_GmCommands.bas, Codigo/ServerConfig.cls, Configuracion.ini
Este cambio permite encarcelar a los usuarios por más tiempo. 
Antes: 240 minutos.
Ahora: 8640 minutos.
=> Cambio en el tiempo de cárcel permitido

Codigo/ModGrupos.bas
Corrijo el orden de los parámetros en la llamada a WriteLocaleMsg, asegurando que el tipo de fuente se pase antes del nombre del remitente. Esto evita errores y permite el correcto funcionamiento en la invitación a un grupo.
=> FIX: Corrección en la llamada a WriteLocaleMsg en InvitarMiembro

Codigo/modHechizos.bas
-fixed and error where druid was not benefiting from the previous patch for summoneable entities https://github.com/ao-org/argentum-online-server/pull/895
-also added the spell property in assets https://github.com/ao-org/argentum-online-assets/commit/92fda6e4a9249742c81f268cb8507f0b6f3c8d42
-corrected a serious error when checking for DañoMagicoEqpSlot instead of DañoMagicoEqpObjIndex which lead to error in modHechizos.PuedeLanzar probably in prod (maybe a crash reason)
-I suggest changing this property "InstrumentoRequerido" to "StaffPower" which is the one that manages this kind of things in the weapons, but make it load in the otDañoMagico
=> fix_DruidAlsoBenefitsFromDMWhenSummoning

Codigo/modHechizos.bas
-Fixed eSameFaction validation for CanUserAttackNpc (i forgot to add it to the exceptions last patch)
=> fix_ArmysAttackingMascots

Codigo/General.bas, Codigo/TCP.bas, Codigo/modUptime.bas, Server.VBP
- Added new module `modUptime` to record server start time and calculate formatted uptime (days, hours, minutes, seconds).
- Initialized uptime tracking at server startup.
- On successful user login, server now sends a welcome message with the current uptime using `FONTTYPE_INFO`.
This allows players to see how long the server has been running continuously since last start
=> feat(server): track server uptime and show on user login

Codigo/Declares.bas, Codigo/FileIO.bas, Codigo/SistemaCombate.bas
-fixed a bug after https://github.com/ao-org/argentum-online-server/commit/60f8bac521a342ff09b43230a412e81d0df31307 that denied the hunter to stay hidden after missing or connecting an attack
-decoupled hardcoded "hunter armor id" for a generic Camouflage boolean property
-in order to get this bonus, the hunter must be hidden, have 100 in "hide" skill and have an armour that has the camouflage property
-also byte ordered the t_ObjData structure to have more performance
=> fix_HunterStaysHidden

git_ignore_case.sh
Normalize cosmetic diffs for VB sources more safely and predictably.
- Use `set -euo pipefail` and quote variables throughout.
- Force `LC_ALL=C` to make case-insensitive diffs deterministic across
locales (fixes `.Pos` vs `.pos` and similar).
- Factor a `make_patch()` helper using unified diffs with `-i`,
`--strip-trailing-cr`, and `--ignore-blank-lines`.
- Tighten file globs (anchored extensions) and skip renames explicitly.
- Apply patches only when non-empty; always end with CRLF via unix2dos.
- Keep the .vbp "first 3 # fields" comparison, implemented via awk.
This reduces noisy status output caused by casing/CR differences and
prevents accidental churn while preserving real content changes.
=> chore(scripts): harden VB case/CRLF normalization

Codigo/General.bas, Codigo/PacketId.bas, Codigo/Protocol.bas, Codigo/Protocol_GmCommands.bas, Codigo/Protocol_Writes.bas, Codigo/modElapsedTime.bas, Codigo/modTime.bas, Server.VBP
- Removed packts eServerTime, eNight, eDay, eSetTime
- Replaced naive subtraction with wrap-aware elapsed calculation
- Use `TicksElapsed32` and `PosMod` to handle 32-bit tick counter wrap (2^32 ms)
- Ensure server always sends a non-negative elapsed time in [0, DayLength)
- This prevents clients from receiving negative world times when GetTickCount wraps
=> fix(protocol): prevent negative world time in PrepareMessageHora

Codigo/MODULO_NPCs.bas, Codigo/Modulo_UsUaRiOs.bas
* Migrated all **stun timing logic** to use wrap-safe raw tick functions.
* `StunEndTime` is now set as an absolute deadline with:
```vb
StunEndTime = AddMod32(GetTickCountRaw(), durationMs)
```
* Updated checks:
* **CanMove / CanAttack** → `TickAfter(nowRaw, StunEndTime)`
* **IsStun** → `Not TickAfter(nowRaw, StunEndTime)`
* **StunPlayer** → applies stun only after immune window using `AddMod32` + `TickAfter`.
* The old implementation used masked `GetTickCount()` and naive comparisons (`>`, `<`).
* When the tick counter wrapped (~24.9 days with masked version), these comparisons went negative and broke stun/cooldown logic.
* This could cause players or NPCs to remain stunned indefinitely or bypass stuns after a wrap.
* All stun-related checks are now **robust across tick wrap** (~49.7 …
=> fix(stun): migrate StunEndTime to wrap-safe raw tick logic
